
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int t_closepar = 10;
  public static final int t_endwhile = 28;
  public static final int t_for = 29;
  public static final int t_true = 33;
  public static final int t_coma = 6;
  public static final int t_not = 48;
  public static final int t_and = 45;
  public static final int t_false = 34;
  public static final int t_endfor = 32;
  public static final int t_notn = 47;
  public static final int t_lt = 41;
  public static final int t_div = 38;
  public static final int t_from = 30;
  public static final int t_or = 46;
  public static final int t_return = 21;
  public static final int t_else = 24;
  public static final int t_closesq = 16;
  public static final int t_read = 18;
  public static final int t_if = 22;
  public static final int t_le = 43;
  public static final int t_const = 7;
  public static final int t_then = 23;
  public static final int t_semicolon = 5;
  public static final int t_diff = 40;
  public static final int t_doubledot = 17;
  public static final int t_minus = 36;
  public static final int t_eq = 8;
  public static final int t_write = 19;
  public static final int EOF = 0;
  public static final int t_beginPrg = 2;
  public static final int error = 1;
  public static final int t_string = 20;
  public static final int t_to = 31;
  public static final int t_openpar = 9;
  public static final int t_intConst = 49;
  public static final int t_time = 37;
  public static final int t_beginfunc = 11;
  public static final int t_gt = 42;
  public static final int t_do = 27;
  public static final int t_ident = 50;
  public static final int t_endPrg = 3;
  public static final int t_bool = 14;
  public static final int t_endfunc = 12;
  public static final int t_endif = 25;
  public static final int t_ge = 44;
  public static final int t_plus = 35;
  public static final int t_opensq = 15;
  public static final int t_doubleq = 39;
  public static final int t_int = 13;
  public static final int t_while = 26;
  public static final int t_prg = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "t_beginPrg",
  "t_endPrg",
  "t_prg",
  "t_semicolon",
  "t_coma",
  "t_const",
  "t_eq",
  "t_openpar",
  "t_closepar",
  "t_beginfunc",
  "t_endfunc",
  "t_int",
  "t_bool",
  "t_opensq",
  "t_closesq",
  "t_doubledot",
  "t_read",
  "t_write",
  "t_string",
  "t_return",
  "t_if",
  "t_then",
  "t_else",
  "t_endif",
  "t_while",
  "t_do",
  "t_endwhile",
  "t_for",
  "t_from",
  "t_to",
  "t_endfor",
  "t_true",
  "t_false",
  "t_plus",
  "t_minus",
  "t_time",
  "t_div",
  "t_doubleq",
  "t_diff",
  "t_lt",
  "t_gt",
  "t_le",
  "t_ge",
  "t_and",
  "t_or",
  "t_notn",
  "t_not",
  "t_intConst",
  "t_ident"
  };
}

